In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.size

15

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.data

In [11]:
type(a)

numpy.ndarray

In [12]:
len(a)

3

In [18]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [19]:
b.dtype

dtype('int32')

In [25]:
c = np.array([[1,2,3],[5,6,7],[12,11.1,25]])
c

array([[ 1. ,  2. ,  3. ],
       [ 5. ,  6. ,  7. ],
       [12. , 11.1, 25. ]])

In [26]:
c.dtype

dtype('float64')

In [28]:
d = np.array([[1,2,3],[5,6,7],[12,11,25]], dtype=complex)
d


array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [ 5.+0.j,  6.+0.j,  7.+0.j],
       [12.+0.j, 11.+0.j, 25.+0.j]])

In [30]:
# zero element array in numpy

e = np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
f = np.ones((1,5))
f

array([[1., 1., 1., 1., 1.]])

In [34]:
np.empty((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [45]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [47]:
aa = np.arange(50)
print(aa)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [48]:
print(np.arange(100000))

[    0     1     2 ... 99997 99998 99999]


In [57]:
o = np.arange(4)
p = np.array([5,10,50,40])
print(p)
print(o)
sub = p-o
print("=========================")
print(sub)
print("========Multiply========")
print(p)
print(o)
mul = p*o
print(mul)
print("========matrix product========")
print(p)
print(o)
mat = p@o
print(mat)
print("========another way of matrix product========")
print(p)
print(o)
amat = p.dot(o)
print(amat)

[ 5 10 50 40]
[0 1 2 3]
[ 5  9 48 37]
========Multiply========
[ 5 10 50 40]
[0 1 2 3]
[  0  10 100 120]
========matrix product========
[ 5 10 50 40]
[0 1 2 3]
230
========another way of matrix product========
[ 5 10 50 40]
[0 1 2 3]
230


In [55]:
#3D array

ap = np.arange(36).reshape(2,3,6)
ap

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])